require 'logger'

# Don't generate README files.
skip_docs

#======================================
# Public
#======================================
lane :build do |options|
  env = options[:env]

  # Android build
  if options[:android]
    build_android(env: env)
  end

  # iOS build
  if options[:ios]
    build_ios(env: env)
  end
end

lane :prebuild do |options|
  platform = options[:platform] || "all"

  # Change to project root directory
  Dir.chdir("..") do
    if platform == "ios"
      sh("npx expo prebuild --clean --platform ios")
    elsif platform == "android"
      sh("npx expo prebuild --clean --platform android")
    else
      sh("npx expo prebuild --clean")
    end
  end
end

#======================================
# Android
#======================================
private_lane :build_android do |options|
  env = options[:env]
  gradle_task = env == "production" ? "clean bundle" : "clean assemble"

  puts "STORE_FILE=#{ENV['STORE_FILE']}"
  puts "STORE_PASSWORD=#{ENV['STORE_PASSWORD']}"
  puts "KEY_ALIAS=#{ENV['KEY_ALIAS']}"
  puts "KEY_PASSWORD=#{ENV['KEY_PASSWORD']}"  

  # gradle(
  #   task: gradle_task,
  #   build_type: "Release",
  #   project_dir: "android",
  #   print_command: false,
  #   properties: {
  #     "android.injected.signing.store.file" => ENV["STORE_FILE"],
  #     "android.injected.signing.store.password" => ENV["STORE_PASSWORD"],
  #     "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
  #     "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
  #   }
  # )

  # # Upload
  # if env == "production"
  #   supply(
  #     track: "alpha",
  #     skip_upload_changelogs: false,
  #     skip_upload_metadata: true,
  #     skip_upload_images: true,
  #     skip_upload_screenshots: true,
  #     json_key: ENV["ANDROID_JSON_KEY_FILE"],
  #     package_name: ENV["EXPO_PUBLIC_APP_PACKAGE_NAME"],
  #     aab: "android/app/build/outputs/bundle/release/app-release.aab",
  #   )
  # else
  #   firebase_app_distribution(
  #     app: ENV["CI_FIREBASE_ANDROID_APP_ID"],
  #     service_credentials_file: "fastlane/credentials.json",
  #     groups: ENV["CI_FIREBASE_ANDROID_GROUPS"],
  #     debug: true,
  #     android_artifact_type: 'APK',
  #     android_artifact_path: "android/app/build/outputs/apk/release/app-release.apk"
  #   )
  # end
end

#======================================
# iOS
#======================================
private_lane :build_ios do |options|
  puts "CI_IOS_TEAM_ID=#{ENV['CI_IOS_TEAM_ID']}"
  puts "CI_IOS_CODE_SIGN_IDENTITY=#{ENV['CI_IOS_CODE_SIGN_IDENTITY']}"
  puts "CI_IOS_PROVISIONING_PROFILE=#{ENV['CI_IOS_PROVISIONING_PROFILE']}"
  puts "CI_IOS_USERNAME=#{ENV['CI_IOS_USERNAME']}"
  puts "CI_IOS_TEAM_NAME=#{ENV['CI_IOS_TEAM_NAME']}"
  puts "CI_IOS_APPLE_ID=#{ENV['CI_IOS_APPLE_ID']}"

  # env = options[:env]
  # app_name = ENV["EXPO_PUBLIC_APP_NAME"].gsub(/\s/, '')
  # xcodeproject_path = "./ios/#{app_name}.xcodeproj"

  # # Select Xcode version
  # sh("ls -la /Applications/ | grep -i xcode") if is_ci?
  # xcode_select("/Applications/Xcode.app") if is_ci?

  # # Set up code signing
  # disable_automatic_code_signing(path: xcodeproject_path)
  # update_code_signing_settings(
  #   use_automatic_signing: false,
  #   path: xcodeproject_path,
  #   team_id: ENV['CI_IOS_TEAM_ID'],
  #   bundle_identifier: ENV["EXPO_PUBLIC_APP_PACKAGE_NAME"],
  #   code_sign_identity: ENV['CI_IOS_CODE_SIGN_IDENTITY'],
  # )

  # # Install provisioning profiles
  # install_provisioning_profiles if is_ci?
  # update_project_provisioning(
  #   xcodeproj: xcodeproject_path,
  #   profile: ENV["CI_IOS_PROVISIONING_PROFILE"],
  #   target_filter: app_name,
  #   build_configuration: "Release",
  # )

  # # Set build number
  # increment_build_number(
  #   xcodeproj: xcodeproject_path,
  #   build_number: ENV.fetch("BUILD_NUMBER", "1")
  # )

  # # Build app
  # build_app(
  #   workspace: "./ios/#{app_name}.xcworkspace",
  #   configuration: "Release",
  #   export_method: env == "production" ? "app-store" : "enterprise",
  #   output_directory: "./ios/build"
  # )

  # # Upload
  # app_name = ENV["EXPO_PUBLIC_APP_NAME"].gsub(/\s/, '')
  # if env == "production"
  #   upload_to_testflight(
  #     username: ENV["CI_IOS_USERNAME"],
  #     team_name: ENV["CI_IOS_TEAM_NAME"],
  #     team_id: ENV["CI_IOS_TEAM_ID"],
  #     app_identifier: ENV["EXPO_PUBLIC_APP_PACKAGE_NAME"],
  #     apple_id: ENV["CI_IOS_APPLE_ID"],
  #     itc_provider: ENV["CI_IOS_APPLE_ID"],
  #     ipa: "ios/build/#{app_name}.ipa",
  #     skip_submission: true,
  #     skip_waiting_for_build_processing: true,
  #   )
  # else
  #   firebase_app_distribution(
  #     env: options[:env],
  #     app: ENV["CI_FIREBASE_IOS_APP_ID"],
  #     service_credentials_file: "fastlane/credentials.json",
  #     groups: ENV["CI_FIREBASE_IOS_GROUPS"],
  #     debug: true,
  #     ipa_path: "ios/build/#{app_name}.ipa"
  #   )
  # end
end
